alias prac="practice"
alias try="cd $HOME/sandbox/try"
alias build="cd $HOME/sandbox/build"
alias learn="cd $HOME/sandbox/learn"
alias practice="cd $HOME/sandbox/practice"
alias tut="cd $HOME/tutorial"
